# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = '2' unless defined? VAGRANTFILE_API_VERSION

################ Paths definitions.
################################################################################
# Absolute paths on the host machine.
ENV['PROJECT_VAGRANTFILE'] = File.expand_path(__FILE__)
host_home_dir = File.expand_path('~')
# Relative paths.
ce_local_home = '.CodeEnigma'
ce_vm_local_home = "#{ce_local_home}/ce-vm"
ce_vm_local_upstream_repo = "#{ce_vm_local_home}/ce-vm-upstream"

# Remote.
ce_vm_upstream_repo = 'https://github.com/codeenigma/ce-vm.git'
ce_vm_upstream_branch = '3.x'

################ Initial processing.
################################################################################

# Clone repo if needed, using triggers.
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.trigger.before :ALL do
    # Create home dirs if needed.
    _ce_home = File.join("#{host_home_dir}", "#{ce_local_home}")
    if(!Dir.exists?("#{_ce_home}"))
      Dir.mkdir("#{_ce_home}")
    end
    _ce_vm_home = File.join("#{host_home_dir}", "#{ce_vm_local_home}")
    if(!Dir.exists?("#{_ce_vm_home}"))
      Dir.mkdir("#{_ce_vm_home}")
    end
    # Clone repo if needed.
    _ce_upstream = File.join("#{host_home_dir}", "#{ce_vm_local_upstream_repo}")
    if(!Dir.exists?("#{_ce_upstream}"))
      info "It looks like this is the first time you are using ce-vm."
      info "Installing into #{_ce_upstream}"
      run "git clone -b #{ce_vm_upstream_branch} #{ce_vm_upstream_repo} #{_ce_upstream}"
      info "Installation finished. Use 'vagrant up' again to retrigger provisioning."
      exit
    end
    # Ensure upgrade path from 2.x to 3.x
    _upstream_file = File.join("#{host_home_dir}", "#{ce_vm_local_upstream_repo}", 'Vagrantfile')
    if(!File.exist?(_upstream_file))
      info "Upgrading to 3.x branch."
      run "git -C #{_ce_upstream} fetch"
      run "git -C #{_ce_upstream} checkout #{ce_vm_upstream_branch}"
      info "Update finished. Use 'vagrant up' again to retrigger provisioning."
      exit
    end
  end
end

# Call actual Vagrantfile.
upstream_file = File.join("#{host_home_dir}", "#{ce_vm_local_upstream_repo}", 'Vagrantfile')
load upstream_file if File.exist?(upstream_file)
