---

############# Development settings. ############################################
# Copy this file at ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml and edit to your
# needs. This settings will be applied to all projects.
################################################################################

ce_vm_auto_update: yes

#php_blackfire: no
#php_blackfire_agent_server_id: ''
#php_blackfire_agent_server_token: ''
#php_blackfire_agent_client_id: ''
#php_blackfire_agent_client_token: ''

#mail_delivery: host

#composer_github_oauth_token: ''

#vagrant_provider: virtualbox