---

- name: Install needed packages.
  apt: "name={{ item }} state=present"
  with_items:
    - "zsh"
    - "git"
    - "wget"

- name: Check if we already have oh-my-zsh.
  stat: path="/home/vagrant/.oh-my-zsh"
  register: oh_my_zsh_install

- name: Clone oh-my-zsh if needed.
  command: >
    git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git /home/vagrant/.oh-my-zsh
  become: true
  become_user: vagrant
  when: not oh_my_zsh_install.stat.exists

- name: Add custom .zshrc file.
  template:
    src: "zshrc.j2"
    dest: "/home/vagrant/.zshrc"
    owner: 'vagrant'
    group: 'vagrant'
    force: yes

- name: Change shell to zsh.
  command: >
    chsh -s /usr/bin/zsh vagrant